[theme]
base="dark"
primaryColor="#00C4FF"
backgroundColor="#0B0C10"
secondaryBackgroundColor="#1F2833"
textColor="#C5C6C7"
font="sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[client]
toolbarMode = "minimal"
showSidebarNavigation = true
